# includes
SHARED_FSPATH=./../../includes

include $(SHARED_FSPATH)/help.mk

# Print
print:
	@echo
	@echo -- TOOL Dummy --
	@echo

## Build
build:
	go build -o bs-dummy .

clean:
	rm -rf bs-dummy

test:
	@echo "TODO"