

print:

	@echo tiup

dep:
	curl --proto '=https' --tlsv1.2 -sSf https://tiup-mirrors.pingcap.com/install.sh | sh

	# Set mirror to https://tiup-mirrors.pingcap.com success
	# Detected shell: zsh
	# Shell profile:  /Users/apple/.zshrc
	# Installed path: /Users/apple/.tiup/bin/tiup

dep-open:
	open /Users/apple/.tiup/
run-play:
	# will bring down everything needed 
	tiup playground

