
print:
	@echo sdk

this-all: this-tool-build this-ex-build
	
this-tool-build:
	cd bs-embed && $(MAKE) this-all

this-ex-build:
	cd bs-embed-ex && $(MAKE) this-all

this-ex-run:
	cd bs-embed-ex && $(MAKE) this-run
