# https://github.com/go-flutter-desktop/hover

# includes
SHARED_FSPATH=./../../includes

include $(SHARED_FSPATH)/help.mk

# Print
print:
	@echo
	@echo -- TOOL Hover --
	@echo

## Build
build: build-clean
	go build -o ./bs-hugo .

build-all: build

build-clean:
	rm -f ./bs-hugo

test:
	@echo TODO



