BOILERPLATE_FSPATH=./../boilerplate

include $(BOILERPLATE_FSPATH)/help.mk
include $(BOILERPLATE_FSPATH)/os.mk
include $(BOILERPLATE_FSPATH)/grpc.mk

## All
this-all: grpc-all
	
	$(MAKE) jsonnet
jsonnet:
	# go get ...

