https://github.com/chriswalz/bit

print:


dep:
	GO111MODULE=on go get github.com/chriswalz/bit@latest;
	GO111MODULE=on go get github.com/chriswalz/bit/bitcomplete@latest;
	COMP_INSTALL=1 bitcomplete;

